# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-13 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200813_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner_ids',
            field=models.ManyToManyField(related_name='restaurants_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
