# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20200813_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='res_food_id',
            new_name='food_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resfooditem',
            name='res_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.Restaurant'),
        ),
    ]
