# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20200814_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'placed'), (2, 'accepted'), (3, 'rejected'), (4, 'dispatched'), (5, 'delivered'), (6, 'cancelled')], default=1, max_length=10),
        ),
    ]
