# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20200817_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='res_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ordereditem',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='ordereditem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='resfooditem',
            old_name='res_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner_ids',
            new_name='owners',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resfooditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
