# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-13 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
